"""
exemplars.py — v3, targeted fixes based on debug_output analysis
"""

EXEMPLARS = {
    "gender_coded": [
        "we need a rockstar ninja developer",
        "looking for a dominant, aggressive sales leader",
        "must be a strong, decisive individual who takes charge",
        "seeking a competitive go-getter who can dominate the market",
        "looking for a guy who can handle pressure",
        "seeking a salesman with a killer instinct for closing deals",
        "we need someone assertive and fearless in negotiations",
        "we want a warrior mentality in our next hire",
        "seeking a gunslinger who thrives under pressure",
        "must be a hustler who grinds without excuses",
        "we need a sharp shooter who hits targets every quarter",
        "looking for a fighter who never backs down from a challenge",
        "we need someone with a killer drive and relentless ambition",
        "the chosen candidate will be a champion who owns the brand single-handedly",
        "must be willing to fight for every deal and never back down",
        "we value bro culture and a locker room environment",
        "looking for a thought leader and industry evangelist",
        "seeking a sensei who can mentor and lead junior team members",
    ],
    "age_coded": [
        "looking for digital natives with youthful energy",
        "recent graduates strongly preferred over experienced candidates",
        "fits naturally into our young, energetic culture",
        "this role is ideal for someone early in their career just starting out",
        "we need fresh blood to energize the team",
        "must be a millennial comfortable with modern consumer trends",
        "must have the energy and drive of someone just starting their career",
        "retirement age candidates are unlikely to be considered for this role",
        "we need someone who can grow with us for the next few decades",
        "the ideal hire is someone not yet set in their ways",
        "experience of zero to two years preferred as seasoned professionals may find this limiting",
        "this position is designed as a launchpad for those just beginning their career",
        "looking for a Gen Z mindset with fresh ideas",
        "candidates over forty five need not apply",
        "looking for someone with no more than three years of experience",
        "we value freshness of thought over decades of experience",
        "must have enthusiasm and curiosity typical of new graduates",
    ],
    "ability_coded": [
        "must be able to work long hours without complaint",
        "should hit the ground running with no hand-holding",
        "requires standing for extended periods, no exceptions",
        "must be able to lift heavy equipment unaided",
        "needs to multitask under constant pressure without breaks",
        "physically fit candidates only need apply",
        "must have perfect vision and hearing for this role",
        "must be available at all hours with no health-related absences",
        "should function at peak performance regardless of personal circumstances",
        "no accommodation for chronic health conditions in this environment",
        "candidates with gaps in employment history will not be considered",
        "must have full mobility and ability to travel internationally on short notice",
        "must be able to stand walk and carry equipment throughout the entire shift",
        "must be able to drive and a valid license is non-negotiable for this role",
        "the role demands someone who never needs to slow down or take a break",
        "must be able to sprint between meetings across a large campus all day",
        "requires near-perfect memory and recall under constant deadline pressure",
    ],
    "cultural_exclusion": [
        "must be a native English speaker",
        "looking for someone who fits our work-hard-play-hard culture",
        "we value work hard play hard culture and after hours bonding",
        "must be comfortable drinking with clients after hours",
        "ideal candidate has a typical American work ethic",
        "should share our traditional family values",
        "must be willing to work through religious holidays without exception",
        "must be comfortable with our beer and pizza startup culture",
        "ideal candidate celebrates Christmas and major Western holidays",
        "we are a tight-knit Western-style team and cultural alignment is key",
        "must be comfortable in a predominantly male environment",
        "fluent English with no regional accent required",
        "candidate should be comfortable with casual profanity in the workplace",
        "we value Sunday availability for team outings and bonding events",
        "must share our founders vision of a Westernized global company",
    ],
    "socioeconomic_exclusion": [
        "must own a personal laptop and reliable car",
        "unpaid internship, ideal for those who don't need a salary",
        "candidates from top-tier colleges only",
        "must be able to relocate at own expense immediately",
        "internship is unpaid but offers excellent exposure",
        "must be willing to work for equity only with no salary in first year",
        "candidates from IIT or IIM only need apply",
        "must be financially stable enough to wait months for first paycheck",
        "candidates should be comfortable with delayed compensation during growth phase",
        "must own a high-performance laptop and professional equipment",
        "should have access to a high-speed personal internet connection at home",
        "experience at a Big 4 or Fortune 500 company is mandatory",
        "candidates from premium MBA programs only will be considered",
        "must be willing to work unpaid trial period before receiving salary",
        "looking for someone with well-connected industry background and family network",
    ],
}

CATEGORY_LABELS = {
    "gender_coded": "Gender-Coded Language",
    "age_coded": "Age-Coded Language",
    "ability_coded": "Ability/Disability-Coded Language",
    "cultural_exclusion": "Cultural Exclusion",
    "socioeconomic_exclusion": "Socioeconomic Exclusion",
}

REWRITE_SUGGESTIONS = {
    "gender_coded": "Use neutral, skill-based language (e.g. 'skilled developer' instead of 'rockstar ninja', 'results-driven' instead of 'dominant/aggressive').",
    "age_coded": "Focus on skills and experience required, not generational framing (e.g. 'proficient with modern tools' instead of 'digital native').",
    "ability_coded": "State the actual physical/functional requirement only if genuinely necessary for the role, and note accommodations are available.",
    "cultural_exclusion": "Avoid framing tied to a specific cultural background; focus on job-relevant communication or collaboration skills.",
    "socioeconomic_exclusion": "Avoid requirements unrelated to job performance (personal equipment, unpaid work, pedigree) unless legally and operationally necessary.",
}
